name: Build

on:
  push:
    branches:
      - main
      - fix-gh-build-action
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install windows dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends software-properties-common
        
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key

        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/kinetic/winehq-kinetic.sources

        sudo apt update && sudo apt upgrade

        sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'

        sudo apt --fix-broken install

        sudo sed -i s@/usr/share/keyrings/@/etc/apt/keyrings/@ /etc/apt/sources.list.d/winehq-focal.sources

        sudo apt update && sudo apt install --install-recommends wine-stable wine64 wine32:i386 wine64
        
        wine --version
        sudo apt-get install -y fakeroot
    - name: Install mono
      run: |
        sudo apt-get install mono-complete
        sudo apt-get update
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
