name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: install rpm
      run: sudo apt-get install -y rpm
    - name: build
      run: npm run make

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run make

  build_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build
      run: npm run make