name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install windows dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends software-properties-common
        
        sudo dpkg --add-architecture i386
        
        curl -L https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.04/Release.key > winehq.key
        sudo apt-key add winehq.key
        
        sudo apt-add-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.04/ ./'
        sudo apt-get update -y
        
        sudo apt-get -y purge software-properties-common libdbus-glib-1-2 python3-dbus python3-gi python3-pycurl python3-software-properties
        
        sudo apt-get install -y wine-stable-i386
        sudo apt-get install -y --no-install-recommends winehq-stable
        
        wine --version
        sudo apt-get install -y fakeroot
    - name: Install mono
      run: |
        sudo apt-get install mono-complete
        sudo apt-get update
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
