name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install windows dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y software-properties-common
        
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
        
        sudo apt update
        sudo apt-get install libjack-jackd2-dev

        sudo apt-get install librtaudio-dev
        sudo dpkg -i sdrpp_ubuntu_focal_amd64.deb
        sudo apt --fix-broken install
        
        sudo apt-get -y upgrade
        sudo apt update
        
        sudo apt-get install -y --install-recommends winehq-devel
        sudo apt-get install -y fakeroot
    - name: Install mono
      run: |
        sudo apt-get install mono-complete
        sudo apt-get update
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
