name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install windows dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        
        sudo mkdir -p /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        
        sudo apt install software-properties-common
        
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -sc)/winehq-$(lsb_release -sc).sources
        
        sudo apt update
        sudo apt-get upgrade -y
        sudo apt update
        
        sudo apt-get install -y --install-recommends winehq-stable
        wine --version
        sudo apt-get install -y fakeroot
    - name: Install mono
      run: |
        sudo apt-get install mono-complete
        sudo apt-get update
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
