name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: install rpm
      run: sudo apt-get install -y rpm
    - name: build
      run: npm run make

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run make

  build_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Set Windows environment
      run: |
        echo 'GYP_MSVS_VERSION=2015' >> $Env:GITHUB_ENV
        echo 'GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
      env:
        PYTHON_VERSION: 3.8
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: install node-gyp
      run: npm install -g node-gyp
    - name: install Windows Build Tools
      run: npm install --g --production windows-build-tools
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run make