name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install packages
      run: |
        sudo apt install wine
        sudo apt-get install mono-complete
        sudo apt-get update
        sudo apt-get install wine32
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist