name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install packages
      run: |
        sudo apt install wine
        sudo apt-get install mono-complete
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run dist
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        title: "Development Build"
        files: |
          *.exe
          *.AppImage