name: CI Electron test

on:
  pull_request:
    branches: [feature-github-actions]
  push:
    branches: [feature-github-actions]

jobs:
  macosBuild:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements and dependencies
        run: |
          brew update
          brew upgrade
          brew install node
          brew install yarn
          echo Node $(node --version)
          echo Yarn $(yarn --version)
          yarn
          yarn global add @electron-forge/cli
          yarn global add ynpx
      - name: Build commit ${{ github.sha }}
        run: |
          yarn make-mac
      - name: Test commit ${{ github.sha }}
        run: |
          yarn test
  linuxBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar gnupg2 rpm dpkg fakeroot
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install -y yarn
          echo Node $(node --version)
          echo Yarn $(yarn --version)
          yarn
          yarn global add @electron-forge/cli
          yarn global add ynpx
      - name: Build commit ${{ github.sha }}
        run: |
          yarn make-linux
      - name: Test commit ${{ github.sha }}
        run: |
          yarn test
  win64Build:
    name: "win64Build"
    runs-on: [windows-latest]
    steps:
      - name: "Add msbuild to PATH"
        uses: microsoft/setup-msbuild@v1.0.2
      - name: "Checkout"
        uses: actions/checkout@v2.3.3
  win32Build:
    name: "win64Build"
    runs-on: [windows-latest]
    steps:
      - name: "Add msbuild to PATH"
        uses: microsoft/setup-msbuild@v1.0.2
      - name: "Checkout"
        uses: actions/checkout@v2.3.3